services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: parts
      POSTGRES_PASSWORD: parts_pass
      POSTGRES_DB: partsdb
    volumes:
      - ./db/data:/var/lib/postgresql/data
      # Mount the whole db folder into the Postgres initialization directory so
      # schema, seeds and import scripts run automatically in alphabetical order.
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
