// Auto-generated by scripts/generate-components-index.js
// Do not edit by hand — run "npm run generate-barrel" to regenerate

export { default as AriaLive } from './AriaLive';
export { default as CircularArrowButton } from './CircularArrowButton';
export { default as CompatibilityGrid } from './CompatibilityGrid';
export { default as CompatibilityModal } from './CompatibilityModal';
export { default as ComponenteEstrelas } from './ComponenteEstrelas';
export { default as ContatoForm } from './ContatoForm';
export { default as CustomDropdown } from './CustomDropdown';
// export { default as DesignSystemComponents } from './DesignSystemComponents'; // Arquivo vazio - comentado temporariamente
export { default as GetStartedButton } from './GetStartedButton';
export { default as GlossarioExpandido } from './GlossarioExpandido';
export { default as LoadingSpinner } from './LoadingSpinner';
export { default as Logo } from './Logo';
export { default as Menu } from './Menu';
export { default as MenuLogin } from './MenuLogin';
export { default as MenuUsuario } from './MenuUsuario';
export { default as PecaCard } from './PecaCard';
export { default as PecasGrid } from './PecasGrid';
export { default as PerfilForm } from './PerfilForm';
export { default as ProExpiryWarning } from './ProExpiryWarning';
export { default as ProductDetailModal } from './ProductDetailModal';
export { default as RatingStars } from './RatingStars';
export { default as SearchForm } from './SearchForm';
export { default as Skeleton } from './Skeleton';
export { default as SmallLoadingModal } from './SmallLoadingModal';
export { default as ThemeToggle } from './ThemeToggle';
export { default as Toast } from './Toast';
export { default as ToggleCar } from './ToggleCar';
export { default as TooltipPortal } from './TooltipPortal';
export { default as WhatsAppButton } from './WhatsAppButton';
